In [ ]:
#CONEXION

In [2]:
!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine
import pandas as pd

database_url = "postgresql://etl_data_pipeline_2500592021_user:va5Onu074qqAOmWJJAbDfgmA7KS1q0I7@dpg-d6vhohaa214c738ab6mg-a.oregon-postgres.render.com/etl_data_pipeline_2500592021"

engine = create_engine(database_url)

test = pd.read_sql("SELECT 1", engine)

print(test)

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 70.0 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11
   ?column?
0         1

In [13]:
import pandas as pd

url = "https://raw.githubusercontent.com/BBulnes20/etl-data-pipeline-2500592021/refs/heads/main/data/raw/E_bodegas.csv"

df_bodegas = pd.read_csv(url)

df_bodegas.head()

  id_bodega       bodega   ubicacion capacidad_m2
0    BOD100   Central 0     Usulután      1292 m2
1    BOD101        Sur 1  San Miguel         2047
2    BOD102    Central 2   Sonsonate       651 m2
3    BOD103  Occidente 3  San Miguel         2250
4    BOD104        Sur 4   Santa Ana          239

In [17]:
import pandas as pd

url = "https://raw.githubusercontent.com/BBulnes20/etl-data-pipeline-2500592021/refs/heads/main/data/raw/E_inventario.csv"

df_inventario = pd.read_csv(url)

df_inventario.head()

  id_inventario id_bodega            item cantidad costo_unitario
0       INV5000    BOD103     Producto 45      359         192.81
1       INV5001    BOD111      Producto 2      419         153.48
2       INV5002    BOD999   Producto 120        58         104.91
3       INV5003    BOD100     Producto 42      422       $ 138.66
4       INV5004    BOD112     Producto 79      257            NaN

In [18]:
import pandas as pd

url = "https://raw.githubusercontent.com/BBulnes20/etl-data-pipeline-2500592021/refs/heads/main/data/raw/E_movimientos.csv"

df_movimientos = pd.read_csv(url)

df_movimientos.head()

  id_movimiento id_inventario tipo_movimiento       fecha cantidad_movimiento
0       MOV9000       INV5000          ajuste  2025-03-05                  15
1       MOV9001       INV5122          ajuste  2024-03-06              73 uds
2       MOV9002       INV5019          salida  2024-05-27                  30
3       MOV9003       INV5110         entrada  2025-01-16                  44
4       MOV9004       INV5152         entrada  2024-08-28                  55

In [ ]:
#EXPLORACION DE DATOS

In [20]:
df_movimientos.shape
df_movimientos.columns
df_movimientos.info()
df_movimientos.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 226 entries, 0 to 225
Data columns (total 5 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id_movimiento        226 non-null    object
 1   id_inventario        220 non-null    object
 2   tipo_movimiento      226 non-null    object
 3   fecha                221 non-null    object
 4   cantidad_movimiento  222 non-null    object
dtypes: object(5)
memory usage: 9.0+ KB

id_movimiento          0
id_inventario          6
tipo_movimiento        0
fecha                  5
cantidad_movimiento    4
dtype: int64

In [ ]:
#LIMPIEZA DE DATOS BODEGAS

In [15]:
bodegas = df_bodegas.copy()

bodegas.columns = bodegas.columns.str.strip().str.lower()

for col in bodegas.select_dtypes(include='object').columns:
    bodegas[col] = bodegas[col].astype(str).str.strip()

bodegas = bodegas.replace(r'^\s*$', pd.NA, regex=True)

# Clean 'capacidad_m2' column: remove ' m2' and convert to numeric
bodegas['capacidad_m2'] = bodegas['capacidad_m2'].astype(str).str.replace(' m2', '', regex=False)
bodegas['capacidad_m2'] = pd.to_numeric(bodegas['capacidad_m2'], errors='coerce')

bodegas = bodegas.drop_duplicates()

print("DataFrame 'bodegas' después de la limpieza:")
print(bodegas.head())
print("Información del DataFrame 'bodegas' después de la limpieza:")
bodegas.info()
print("Valores nulos en 'bodegas' después de la limpieza:")
print(bodegas.isnull().sum())

DataFrame 'bodegas' después de la limpieza:
  id_bodega       bodega   ubicacion  capacidad_m2
0    BOD100    Central 0    Usulután          1292
1    BOD101        Sur 1  San Miguel          2047
2    BOD102    Central 2   Sonsonate           651
3    BOD103  Occidente 3  San Miguel          2250
4    BOD104        Sur 4   Santa Ana           239
Información del DataFrame 'bodegas' después de la limpieza:
<class 'pandas.core.frame.DataFrame'>
Index: 18 entries, 0 to 17
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id_bodega     18 non-null     object
 1   bodega        18 non-null     object
 2   ubicacion     18 non-null     object
 3   capacidad_m2  18 non-null     int64
dtypes: int64(1), object(3)
memory usage: 720.0+ bytes
Valores nulos en 'bodegas' después de la limpieza:
id_bodega       0
bodega          0
ubicacion       0
capacidad_m2    0
dtype: int64

In [ ]:
#LIMPIEZA DE DATOS DE INVENTARIO

In [19]:
inventario = df_inventario.copy()

inventario.columns = inventario.columns.str.strip().str.lower()

for col in inventario.select_dtypes(include='object').columns:
    inventario[col] = inventario[col].astype(str).str.strip()

inventario = inventario.replace(r'^\s*$', pd.NA, regex=True)

# Clean 'costo_unitario' column: remove '$' and convert to numeric
inventario['costo_unitario'] = inventario['costo_unitario'].astype(str).str.replace('$', '', regex=False)
inventario['costo_unitario'] = pd.to_numeric(inventario['costo_unitario'], errors='coerce')

# Clean 'cantidad' column: remove non-numeric characters and convert to numeric
inventario['cantidad'] = inventario['cantidad'].astype(str).str.replace(r'[^0-9.]', '', regex=True)
inventario['cantidad'] = pd.to_numeric(inventario['cantidad'], errors='coerce')

inventario = inventario.drop_duplicates()

print("DataFrame 'inventario' después de la limpieza:")
print(inventario.head())
print("Información del DataFrame 'inventario' después de la limpieza:")
inventario.info()
print("Valores nulos en 'inventario' después de la limpieza:")
print(inventario.isnull().sum())

DataFrame 'inventario' después de la limpieza:
  id_inventario id_bodega          item  cantidad  costo_unitario
0       INV5000    BOD103   Producto 45     359.0          192.81
1       INV5001    BOD111    Producto 2     419.0          153.48
2       INV5002    BOD999  Producto 120      58.0          104.91
3       INV5003    BOD100   Producto 42     422.0          138.66
4       INV5004    BOD112   Producto 79     257.0             NaN
Información del DataFrame 'inventario' después de la limpieza:
<class 'pandas.core.frame.DataFrame'>
Index: 160 entries, 0 to 159
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_inventario   160 non-null    object
 1   id_bodega       160 non-null    object
 2   item            160 non-null    object
 3   cantidad        153 non-null    float64
 4   costo_unitario  149 non-null    float64
dtypes: float64(2), object(3)
memory usage: 7.5+ KB
Valores nulos en 'inventario' después de la limpieza:
id_inventario      0
id_bodega          0
item               0
cantidad           7
costo_unitario    11
dtype: int64

In [ ]:
#LIMPIEZA DE DATOS MOVIMIENTOS

In [21]:
movimientos = df_movimientos.copy()

movimientos.columns = movimientos.columns.str.strip().str.lower()

for col in movimientos.select_dtypes(include='object').columns:
    movimientos[col] = movimientos[col].astype(str).str.strip()

movimientos = movimientos.replace(r'^\s*$', pd.NA, regex=True)

# Clean 'cantidad_movimiento' column: remove non-numeric characters and convert to numeric
movimientos['cantidad_movimiento'] = movimientos['cantidad_movimiento'].astype(str).str.replace(r'[^0-9.]', '', regex=True)
movimientos['cantidad_movimiento'] = pd.to_numeric(movimientos['cantidad_movimiento'], errors='coerce')

# Convert 'fecha' to datetime
movimientos['fecha'] = pd.to_datetime(movimientos['fecha'], errors='coerce')

movimientos = movimientos.drop_duplicates()

print("DataFrame 'movimientos' después de la limpieza:")
print(movimientos.head())
print("Información del DataFrame 'movimientos' después de la limpieza:")
movimientos.info()
print("Valores nulos en 'movimientos' después de la limpieza:")
print(movimientos.isnull().sum())

DataFrame 'movimientos' después de la limpieza:
  id_movimiento id_inventario tipo_movimiento      fecha  cantidad_movimiento
0       MOV9000       INV5000          ajuste 2025-03-05                 15.0
1       MOV9001       INV5122          ajuste 2024-03-06                 73.0
2       MOV9002       INV5019          salida 2024-05-27                 30.0
3       MOV9003       INV5110         entrada 2025-01-16                 44.0
4       MOV9004       INV5152         entrada 2024-08-28                 55.0
Información del DataFrame 'movimientos' después de la limpieza:
<class 'pandas.core.frame.DataFrame'>
Index: 220 entries, 0 to 219
Data columns (total 5 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id_movimiento        220 non-null    object
 1   id_inventario        220 non-null    object
 2   tipo_movimiento      220 non-null    object
 3   fecha                202 non-null    datetime64[ns]
 4   cantidad_movimiento  216 non-null    float64
dtypes: datetime64[ns](1), float64(1), object(3)
memory usage: 10.3+ KB
Valores nulos en 'movimientos' después de la limpieza:
id_movimiento           0
id_inventario           0
tipo_movimiento         0
fecha                  18
cantidad_movimiento     4
dtype: int64

In [ ]:
#SEPARAR DATOS EN VALIDOS Y RECHAZADOS BODEGAS

In [23]:
bodegas_validas = bodegas[bodegas['capacidad_m2'].notna()].copy()
bodegas_rechazadas = bodegas[bodegas['capacidad_m2'].isna()].copy()

print("DataFrame 'bodegas_validas' (validas):")
print(bodegas_validas.head())
print("Número de filas válidas:", len(bodegas_validas))

print("\nDataFrame 'bodegas_rechazadas' (rechazadas):")
print(bodegas_rechazadas.head())
print("Número de filas rechazadas:", len(bodegas_rechazadas))

if bodegas_rechazadas.empty:
    print("\n¡Excelente! No se encontraron filas rechazadas en el DataFrame 'bodegas' según la validación de 'capacidad_m2'.")

DataFrame 'bodegas_validas' (validas):
  id_bodega       bodega   ubicacion  capacidad_m2
0    BOD100    Central 0    Usulután          1292
1    BOD101        Sur 1  San Miguel          2047
2    BOD102    Central 2   Sonsonate           651
3    BOD103  Occidente 3  San Miguel          2250
4    BOD104        Sur 4   Santa Ana           239
Número de filas válidas: 18

DataFrame 'bodegas_rechazadas' (rechazadas):
Empty DataFrame
Columns: [id_bodega, bodega, ubicacion, capacidad_m2]
Index: []
Número de filas rechazadas: 0

¡Excelente! No se encontraron filas rechazadas en el DataFrame 'bodegas' según la validación de 'capacidad_m2'.

In [ ]:
#SEPARAR DATOS EN VALIDOS Y RECHAZADOS INVENTARIO

In [24]:
inventario_validos = inventario[inventario['cantidad'].notna() & inventario['costo_unitario'].notna()].copy()
inventario_rechazados = inventario[inventario['cantidad'].isna() | inventario['costo_unitario'].isna()].copy()

print("DataFrame 'inventario_validos' (validos):")
print(inventario_validos.head())
print("Número de filas válidas:", len(inventario_validos))

print("\nDataFrame 'inventario_rechazados' (rechazadas):")
print(inventario_rechazados.head())
print("Número de filas rechazadas:", len(inventario_rechazados))

if inventario_rechazados.empty:
    print("\n¡Excelente! No se encontraron filas rechazadas en el DataFrame 'inventario'.")
else:
    print("\nSe encontraron filas rechazadas en el DataFrame 'inventario' basadas en valores nulos en 'cantidad' o 'costo_unitario'.")

DataFrame 'inventario_validos' (validos):
  id_inventario id_bodega          item  cantidad  costo_unitario
0       INV5000    BOD103   Producto 45     359.0          192.81
1       INV5001    BOD111    Producto 2     419.0          153.48
2       INV5002    BOD999  Producto 120      58.0          104.91
3       INV5003    BOD100   Producto 42     422.0          138.66
5       INV5005       nan   Producto 57     488.0          228.60
Número de filas válidas: 143

DataFrame 'inventario_rechazados' (rechazadas):
   id_inventario id_bodega          item  cantidad  costo_unitario
4        INV5004    BOD112   Producto 79     257.0             NaN
9        INV5009    BOD115    Producto 4       NaN          277.58
22       INV5022    BOD111   Producto 58     339.0             NaN
26       INV5026    BOD117   Producto 47       NaN           29.53
48       INV5048    BOD105  Producto 100      12.0             NaN
Número de filas rechazadas: 17

Se encontraron filas rechazadas en el DataFrame 'inventario' basadas en valores nulos en 'cantidad' o 'costo_unitario'.

In [ ]:
#SEPARAR DATOS EN VALIDOS Y RECHAZADOS MOVIMIENTOS

In [25]:
movimientos_validos = movimientos[movimientos['fecha'].notna() & movimientos['cantidad_movimiento'].notna()].copy()
movimientos_rechazados = movimientos[movimientos['fecha'].isna() | movimientos['cantidad_movimiento'].isna()].copy()

print("DataFrame 'movimientos_validos' (validos):")
print(movimientos_validos.head())
print("Número de filas válidas:", len(movimientos_validos))

print("\nDataFrame 'movimientos_rechazados' (rechazadas):")
print(movimientos_rechazados.head())
print("Número de filas rechazadas:", len(movimientos_rechazados))

if movimientos_rechazados.empty:
    print("\n¡Excelente! No se encontraron filas rechazadas en el DataFrame 'movimientos'.")
else:
    print("\nSe encontraron filas rechazadas en el DataFrame 'movimientos' basadas en valores nulos en 'fecha' o 'cantidad_movimiento'.")

DataFrame 'movimientos_validos' (validos):
  id_movimiento id_inventario tipo_movimiento      fecha  cantidad_movimiento
0       MOV9000       INV5000          ajuste 2025-03-05                 15.0
1       MOV9001       INV5122          ajuste 2024-03-06                 73.0
2       MOV9002       INV5019          salida 2024-05-27                 30.0
3       MOV9003       INV5110         entrada 2025-01-16                 44.0
4       MOV9004       INV5152         entrada 2024-08-28                 55.0
Número de filas válidas: 198

DataFrame 'movimientos_rechazados' (rechazadas):
   id_movimiento id_inventario tipo_movimiento      fecha  cantidad_movimiento
6        MOV9006       INV5115        traslado        NaT                 39.0
19       MOV9019       INV5132          salida        NaT                 32.0
22       MOV9022       INV9999        traslado 2025-03-18                  NaN
39       MOV9039       INV5101         entrada        NaT                 18.0
48       MOV9048       INV5088          ajuste        NaT                 19.0
Número de filas rechazadas: 22

Se encontraron filas rechazadas en el DataFrame 'movimientos' basadas en valores nulos en 'fecha' o 'cantidad_movimiento'.

In [ ]:
#EXPORTAR ARCHIVOS

In [34]:
bodegas_validas.to_csv("bodegas_curated.csv", index = False)

bodegas_rechazadas.to_csv("bodegas_rejects.csv", index = False)

In [35]:
inventario_validos.to_csv("inventario_curated.csv", index = False)

inventario_rechazados.to_csv("inventario_rejects.csv", index = False)

In [36]:
movimientos_validos.to_csv("movimientos_curated.csv", index = False)

movimientos_rechazados.to_csv("movimientos_rejects.csv", index = False)

In [ ]:
#CONECTAR CON POSTGRESQL

In [37]:
!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine
import pandas as pd

database_url = "postgresql://etl_data_pipeline_2500592021_user:va5Onu074qqAOmWJJAbDfgmA7KS1q0I7@dpg-d6vhohaa214c738ab6mg-a.oregon-postgres.render.com/etl_data_pipeline_2500592021"

engine = create_engine(database_url)

test = pd.read_sql("SELECT 1", engine)

print(test)

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Requirement already satisfied: psycopg2-binary in /usr/local/lib/python3.12/dist-packages (2.9.11)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
   ?column?
0         1

In [ ]:
#CARGAR DATOS

In [45]:
bodegas_validas.to_sql(
    'bodegas_curated',
    engine,
    if_exists='append',
    index=False
)

bodegas_rechazadas.to_sql(
    'bodegas_rejects',
    engine,
    if_exists='append',
    index=False
)

0

In [40]:
inventario_validos.to_sql(
    'inventario_curated',
    engine,
    if_exists='append',
    index=False
)

inventario_rechazados.to_sql(
    'inventario_rejects',
    engine,
    if_exists='append',
    index=False
)

17

In [41]:
movimientos_validos.to_sql(
    'movimientos_curated',
    engine,
    if_exists='append',
    index=False
)

movimientos_rechazados.to_sql(
    'movimientos_rejects',
    engine,
    if_exists='append',
    index=False
)

22

In [ ]:
#VALIDAR CARGA

In [46]:
pd.read_sql(
    "SELECT * FROM bodegas_curated LIMIT 10",
    engine
)

  id_bodega       bodega    ubicacion  capacidad_m2
0    BOD100    Central 0     Usulután          1292
1    BOD101        Sur 1   San Miguel          2047
2    BOD102    Central 2    Sonsonate           651
3    BOD103  Occidente 3   San Miguel          2250
4    BOD104        Sur 4    Santa Ana           239
5    BOD105    Central 5  La Libertad          1546
6    BOD106    Central 6   San Miguel          1783
7    BOD107  Occidente 7  La Libertad          2181
8    BOD108    Oriente 8    Santa Ana          1359
9    BOD109    Oriente 9    Santa Ana          2097

In [47]:
pd.read_sql(
    "SELECT * FROM inventario_curated LIMIT 10",
    engine
)

  id_inventario id_bodega          item  cantidad  costo_unitario
0       INV5000    BOD103   Producto 45     359.0          192.81
1       INV5001    BOD111    Producto 2     419.0          153.48
2       INV5002    BOD999  Producto 120      58.0          104.91
3       INV5003    BOD100   Producto 42     422.0          138.66
4       INV5005       nan   Producto 57     488.0          228.60
5       INV5006    BOD111   Producto 88     436.0          333.93
6       INV5007    BOD111   Producto 64     401.0          167.73
7       INV5008    BOD106   Producto 98     173.0          307.79
8       INV5010    BOD102   Producto 18      53.0           93.98
9       INV5011    BOD104   Producto 89     473.0          267.21

In [48]:
pd.read_sql(
    "SELECT * FROM movimientos_curated LIMIT 10",
    engine
)

  id_movimiento id_inventario tipo_movimiento      fecha  cantidad_movimiento
0       MOV9000       INV5000          ajuste 2025-03-05                 15.0
1       MOV9001       INV5122          ajuste 2024-03-06                 73.0
2       MOV9002       INV5019          salida 2024-05-27                 30.0
3       MOV9003       INV5110         entrada 2025-01-16                 44.0
4       MOV9004       INV5152         entrada 2024-08-28                 55.0
5       MOV9005       INV5133        traslado 2024-03-21                 17.0
6       MOV9007       INV5093          ajuste 2025-06-15                 48.0
7       MOV9008       INV5119         entrada 2025-01-31                  3.0
8       MOV9009       INV5112          ajuste 2025-07-04                 37.0
9       MOV9010       INV5002          salida 2024-11-09                 17.0